---
- name: create Ec2 Instances
  hosts: localhost
  gather_facts: no
  vars_files:
    - /home/ahmed/Desktop/dolfined/keys.yml
  tasks:
    - name: creating new EC2 Instances
      amazon.aws.ec2_instance:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: us-east-2
        key_name: awsec2key
        instance_type: t2.micro
        image_id: ami-02d1e544b84bf7502
        security_group: default
        count: 2
        vpc_subnet_id: subnet-0332646e33b3106ca
        network:
          assign_public_ip: true
        tags:
          Name: Dolfined
