---
- name: dealing with EC2/EBS volumes
  hosts: localhost
  tasks:
    - name: attach a volume to an existing EC2 Instance
      amazon.aws.ec2_vol:
        instance: i-07d616fae6894aa7b
        volume_size: 10
        device_name: /dev/sdf
        region: us-east-2
        delete_on_termination: yes

    - name: launch a new instance and attach a volume to it
        amazon.aws.ec2_instance:
          region: us-east-2
          key_name: awsec2key
          image_id: ami-02d1e544b84bf7502
          wait: yes
          wait_timeout: 600
          count: 1
          tags:
            Name: Ansible123
        register: ec2

    - name: check the status of the created instance
      amazon.aws.ec2_instance_info:
        region: us-east-2
        filters:
          "tag:Name": Ansible_test
      register: state
      until: state.instances[0].state.name=="running"
      retries: 10
      delay: 30

    - name: attach the new volume to the created instance
      amazon.aws.ec2_vol:
        instance: "{{ item }}"
        volume_size: 15
        region: us-east-2
      loop: "{{ ec2.instance_ids }}"
      register: ec2_vol
