---
- name: Dealing with S3 Buckets inside AWS
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create a simple S3 bucket
      amazon.aws.s3_bucket:
        region: us-east-2
        name: dolfinedbucket123456
        state: present
        encryption: "aws:kms"
        acl: public-read
        tags:
          Name: dolfined_ansible
      register: output
    - debug: var=output


    - name: Create a bucket with public policy block configuration
      amazon.aws.s3_bucket:
        region: us-east-2
        name: dolfinedbucket456789
        state: present
        public_access:
            block_public_acls: true
            ignore_public_acls: true
      register: output2
    - debug: var=output2

###############################################################################################
  ---
  - name: Deleting S3 Buckets inside AWS
    hosts: localhost
    gather_facts: no
    vars:
      buckets: [ "dolfinedbucket123456","dolfinedbucket456789" ]
    tasks:
    - name: Remove the above created S3 buckets and any keys it contains
      amazon.aws.s3_bucket:
        name: "{{item}}"
        state: absent
        force: yes
      loop: "{{ buckets }}"
