---
- name: Provision EC2 Instances
  hosts: localhost
  gather_facts: no
  vars_files:
    - /home/ahmed/Desktop/dolfined/keys.yml
  tasks:
    - name: Start Ec2 Instance with tag
      amazon.aws.ec2_instance:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: us-east-2
        state: started
        tags:
          Name: Dolfined

    - name: stop Ec2 Instance with tag
      amazon.aws.ec2_instance:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: us-east-2
        state: stopped
        tags:
          Name: Dolfined123
