---
- name: Gather information about instances with different options
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Gather information about all instances
      amazon.aws.ec2_instance_info:
        region: us-east-2
      register: output1
    - debug: var=output1.instances

    - name: Gather information about all instances in specific AZ
      amazon.aws.ec2_instance_info:
        region: us-east-2
        filters:
          availability-zone: us-east-2b
      register: output2
    - debug: var=output2

    - name: Gather information about a particular instance using ID
      amazon.aws.ec2_instance_info:
        region: us-east-2
        instance_ids:
          - i-0ac4d9b09b45c633c
      register: output3
    - debug: var=output3

    - name: Gather information about any instance with a tag key Name and value Example
      amazon.aws.ec2_instance_info:
        region: us-east-2
        filters:
          "tag:Name": Dolfined
      register: output4
    - debug: var=output4

    - name: Gather information about any instance in states "shutting-down", "stopping", "stopped"
      amazon.aws.ec2_instance_info:
        region: us-east-2
        filters:
          instance-state-name: [ "stopped" ]
      register: output5
    - debug: var=output5

###################################
---
- name: Gather information and filter output to exact required information
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Gather information about all instances
      amazon.aws.ec2_instance_info:
        region: us-east-2
      register: output
    - set_fact:
        instance_id: "{{output.instances[0].instance_id}}" # here we got the first instance id from the output
    - debug: var=instance_id
