apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: bXlzcWxwYXNzd29yZA== # base64 encoded 'mysqlpassword'
  MYSQL_DATABASE: d29yZHByZXNz # base64 encoded 'wordpress'
  MYSQL_USER: d29yZHByZXNz # base64 encoded 'wordpress'
  MYSQL_PASSWORD: d29yZHByZXNzcGFzcw== # base64 encoded 'wordpresspass'
